### ISSUE TITLE
[PyCharm Community] Failed to build from source

### ISSUE THREAD

**Issue by rafi612** [M3DZIK/rpm#6]
PyCharm Community throwing error when building from source. Arch Linux seems to have same problem (Package is marked as out of date). Arch Linux has package version 2024.1.5 (241.18968.29)

Link to Arch Linux package: https://gitlab.archlinux.org/archlinux/packaging/packages/pycharm-community-edition

**Comment by jerome-benoit** [comment]
Hello, 

Is it related to the build failure: https://copr.fedorainfracloud.org/coprs/medzik/jetbrains/package/pycharm-community/? 

Unfortunately, the build logs are not longer available.

**Comment by rafi612** [comment]
Seems to COPR removing build logs after some time. @M3DZIK should rerun build soon.

**Comment by M3DZIK** [comment]
I'm launched a rebuild

**Comment by M3DZIK** [comment]
I started the build again

**Comment by jerome-benoit** [comment]
Looks like a missing class export: 

```
Caused by: java.lang.ClassNotFoundException: com.maddyhome.idea.copyright.vcs.UpdateCopyrightCheckinHandlerFactory PluginClassLoader(plugin=PluginDescriptor(name=Copyright, id=com.intellij.copyright, moduleName=intellij.copyright.vcs, descriptorPath=intellij.copyright.vcs.xml, path=~/build/BUILD/intellij-community/out/pycharm-ce/temp/dev-run/PyCharmCore/PyCharmCore/plugins/copyright, version=242.21829.SNAPSHOT, package=com.maddyhome.idea.copyright.vcs, isBundled=true), packagePrefix=com.maddyhome.idea.copyright.vcs., state=active, parents=PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=~/build/BUILD/intellij-community/out/pycharm-ce/temp/dev-run/PyCharmCore/PyCharmCore/lib, version=242.21829.SNAPSHOT, package=null, isBundled=true), PluginDescriptor(name=Copyright, id=com.intellij.copyright, descriptorPath=plugin.xml, path=~/build/BUILD/intellij-community/out/pycharm-ce/temp/dev-run/PyCharmCore/PyCharmCore/plugins/copyright, version=242.21829.SNAPSHOT, package=null, isBundled=true), )
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1464)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass$default(ComponentManagerImpl.kt:1460)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:887)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:21)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:51)
	... 77 more
```

I do find the PyCharm source code on https://github.com/JetBrains. I doubt it's easily fixable without JetBrains cooperation.

**Comment by rafi612** [comment]
I'm wondering how JetBrains build his own builds. Build instructions are very poor, we only know that we must run `installers.cmd` (for IntelliJ) or `python/intallers.cmd` (for PyCharm) and also we know several build variables. Maybe we should report this on YouTrack?

**Comment by jerome-benoit** [comment]
> Maybe we should report this on YouTrack?

Someone familiar with PyCharm RPM packaging should: version introducing the issue, ... if nobody has already done it.

**Comment by M3DZIK** [comment]
Fixed in https://github.com/M3DZIK/rpm/commit/c8b670799cbfd13726493ceffa492ebcc6d24cc9 commit
